package com.udea.paletas_service.persistencia;
// Generated 1/06/2017 09:43:20 AM by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paleta generated by hbm2java
 */
@Entity
@Table(name="paleta"
    ,catalog="skady"
)
public class Paleta  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private int tipoPaleta;
     private double precio;

    public Paleta() {
    }

    public Paleta(String nombre, int tipoPaleta, double precio) {
       this.nombre = nombre;
       this.tipoPaleta = tipoPaleta;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODIGO", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="TIPO_PALETA", nullable=false)
    public int getTipoPaleta() {
        return this.tipoPaleta;
    }
    
    public void setTipoPaleta(int tipoPaleta) {
        this.tipoPaleta = tipoPaleta;
    }

    
    @Column(name="PRECIO", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + Objects.hashCode(this.codigo);
        hash = 29 * hash + Objects.hashCode(this.nombre);
        hash = 29 * hash + this.tipoPaleta;
        hash = 29 * hash + (int) (Double.doubleToLongBits(this.precio) ^ (Double.doubleToLongBits(this.precio) >>> 32));
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Paleta other = (Paleta) obj;
        if (this.tipoPaleta != other.tipoPaleta) {
            return false;
        }
        if (Double.doubleToLongBits(this.precio) != Double.doubleToLongBits(other.precio)) {
            return false;
        }
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Paleta{" + "codigo=" + codigo + ", nombre=" + nombre + ", tipoPaleta=" + tipoPaleta + ", precio=" + precio + '}';
    }




}


